ADD: 유저 좋아요 기능 추가, MODIFY: 데이터베이스 초기화후 마이그레이션
wecode-bootcamp-korea/enter_cloud-backend pull request #7
Opened 2021-01-17 05:56 UTC by ddalkigum

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 좋아요 기능 추가
- 마이그레이션 다시 진행
- 파일이름 변경
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 좋아요 기능, ( post, delete ) 메서드 이용해서 추가, 
- 데이터 베이스 다시 생성 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-18 10:25 UTC, ulfrid requested changes

2021-01-18 10:25 UTC, devops-andrew commented on spaces/views.py
> +            return HttpResponse("KEY_ERROR")
요 response 들이 매우 불편하군요 ㅋㅋㅋ
메세지로 줄거면 JsonResponse를 
HttpResponse로 줄거면  status_code를 주시는걸로 결정 부탁드립니다.

2021-01-18 10:25 UTC, ulfrid commented on spaces/views.py
> +            return HttpResponse("KEY_ERROR")
이렇게 매번 생성하고 지우는 방법도 있지만~
한번만 생성하고, 수정하는 방법도 있습니다.
테이블 수명을 길게 가져가기에는 매번 생성 삭제하는것보다. 수정으로 조치하는게 간단할 수도 있습니다.
또한, 호출 메서드를 하나로 통합하여, 토글기능 처럼 생성 여부에 의한 생성, 상태에 따른 변경을 해볼 수 도 있습니다.
모델에 is_liked라는 컬럼을 추가해서 True, False로 관리해보는건 어떨까요? 
그렇게 하면 삭제하지 않고, 호출에 따라 판별 할 수 있습니다.

2021-01-18 10:44 UTC, ddalkigum commented on spaces/views.py
> +            return HttpResponse("KEY_ERROR")
아아... 이걸로 메시지를 주고 받는 줄 알았습니다 ㅋㅋㅋㅋ

2021-01-18 10:46 UTC, ddalkigum commented on spaces/views.py
> +            return HttpResponse("KEY_ERROR")
너무 좋을 것 같에요!! 
메서드를 post, delete를 사용해서 하는게 겹치는 부분이 너무 많아서 고민했엇는데 
그렇게 하면 좋을 것같에요

2021-01-18 14:02 UTC, ulfrid requested changes
확인 바랍니다~!

2021-01-18 14:02 UTC, ulfrid commented on spaces/views.py
> +            Like.objects.create(user = user, space = space, is_liked = True)
```suggestion
          if Like.objects.filter(user = user, space = space).exists():
              like     = Like.objects.get(user = user, space = space)
              if like.is_liked == True:
                  like.is_liked = False
                  like.save()
                  return JsonResponse({"message":"UNLIKE"}, status = 200)
              like.is_liked = True
              like.save()
              return JsonResponse({"message":"LIKE"}, status = 200)
          Like.objects.create(user = user, space = space, is_liked = True)
```
Exception으로 처리한다는것은 에러를 의미하는데, 
거기서 라이크를 생성하는건 부자연스럽습니다.  
위와 같이 조건 처리 하는게 더 보기 좋습니다.

2021-01-18 14:24 UTC, ddalkigum commented on spaces/views.py
> +            Like.objects.create(user = user, space = space, is_liked = True)
알겠습니다 😁
다른 방법도 조금만 더 생각해보고 푸시 하겠습니다

2021-01-19 01:03 UTC, ddalkigum commented
like.is_liked가 반복되서 불편한 느낌이 들어서 여러가지로 수정해봤는데 
불편한 마음이 사라지지 않아요 😂
지훈님이 제시해주신 방법으로 가겠습니다

2021-01-19 05:15 UTC, ulfrid commented
LGTM 👍

2021-01-19 05:15 UTC, merged